/// Centralised configuration – all keys come from compile-time Dart defines
/// so they are baked into the JS bundle and never exposed in plain-text files.
///
/// Pass them at build time:
///   flutter build web \
///     --dart-define=GEMINI_API_KEY=xxx \
///     --dart-define=SHOPIFY_STORE_DOMAIN=yourstore.myshopify.com \
///     --dart-define=SHOPIFY_STOREFRONT_TOKEN=xxx
class AppConfig {
  // ── Gemini ──────────────────────────────────────────────────────────────
  static const String geminiApiKey = String.fromEnvironment(
    'GEMINI_API_KEY',
    defaultValue: 'AIzaSyB5ywD4X5PAi8NuASUHI-97rLhHSczCVko',
  );

  // ── Shopify Storefront API ───────────────────────────────────────────────
  static const String shopifyStoreDomain = String.fromEnvironment(
    'SHOPIFY_STORE_DOMAIN',
    defaultValue: 'rever-david-app.myshopify.com',
  );
  static const String shopifyStorefrontToken = String.fromEnvironment(
    'SHOPIFY_STOREFRONT_TOKEN',
    defaultValue: '77a102f7724388f50875613a4335703b',
  );

  // ── Firebase (injected via firebase_options.dart generated by FlutterFire) ─
  static const String firebaseApiKey = 'AIzaSyBomcB7dY3QFxjK5IFjZfXxBPpUeoCup-c';
  static const String firebaseAuthDomain = 'rever-c494a.firebaseapp.com';
  static const String firebaseProjectId = 'rever-c494a';
  static const String firebaseStorageBucket = 'rever-c494a.firebasestorage.app';
  static const String firebaseMessagingSenderId = '187524738073';
  static const String firebaseAppId = '1:187524738073:web:2f01e87ad54e9c54770e88';
}
